export const grille = () => {
    console.log(`   +---+---+---+---+---+---+---+`)
    console.log(` F |   |   |   |   |   |   |   |`)
    console.log(`   +---+---+---+---+---+---+---+`)
    console.log(` E |   |   |   |   |   |   |   |`)
    console.log(`   +---+---+---+---+---+---+---+`)
    console.log(` D |   |   |   |   |   |   |   |`)
    console.log(`   +---+---+---+---+---+---+---+`)
    console.log(` C |   |   |   |   |   |   |   |`)
    console.log(`   +---+---+---+---+---+---+---+`)
    console.log(` B |   |   |   |   |   |   |   |`)
    console.log(`   +---+---+---+---+---+---+---+`)
    console.log(` A |   |   |   |   |   |   |   |`)
    console.log(`   +---+---+---+---+---+---+---+`)
    console.log(`     1   2   3   4   5   6   7  `)
}
